### ISSUE TITLE
current set from 16 A to 6A and no change possible

### ISSUE THREAD

**Issue by mebi2024** [dannerph/homeassistant-keba#37]
Since last Update to 4.3.0 my current (number.keba_p30_charging_current) is set to 6 ampere. Before is was 16 ampere. If I change the 6 to 16 in the dialog box it is reset after a frew seconds to 6. 
I also tried to change the value 6 to 16 in services.yaml:
/config/custom_components/keba/services.yaml
line 52: "default: 6" changed to "default: 16"
line 88: "default: 6" changed to "default: 16"
but there is no change after reload KEBA customization and restart of home assistant. How can I change back the current to 16 A?

**Comment by dannerph** [comment]
Hi @mebi2024,

I assume you operate a Keba P30 charging station? Could you please provide the product string (KC-P30-XXXXXXXX-000) e.g. from the web interface of your charging station.

Could you confirm that the failsafe mode is disabled? (check the corresponding sensor in HA)

BR
Philipp

**Comment by mebi2024** [comment]
Hi @dannerph ,
thank you for the quick response.

The product string is:  KC-P30-ES2400E2-L0R  (x-series)

failsafe mode is not really known to me, sorry (newbie in home assistant since Nov. 2024).  
binary_sensor.keba_p30_failsafe_mode = "sicher"

Dec. 31st until Jan. 4th failsafe was "unsicher".
Jan 4th until Jan 7th failsafe was "nicht verfügbar"
failsafe since Jan 7th "sicher"
if failsafe mode has to be changed, please let me know how.

Thank you
Martin

**Comment by dannerph** [comment]
Ok, it seems failsafe mode is activate on your charging station. Depending on the failsafe settings, it will automatically revert your set current.
Go to developer menu to execute a service with the following settings:
![grafik](https://github.com/user-attachments/assets/3850ec93-0503-4d73-8018-90ae7754dc5b)
Afterwards failsafe mode should be permanently off and setting current should be working again.
If it does not work, please reopen the issue

**Comment by mebi2024** [comment]
Good morning,
during a car was loading yesterday evening I got the error message: 
"Die Aktion keba_set_failsafe konnte nicht ausgeführt werden. Unknown error" - see screenshot, but it is still the same this morning after restarting the KEBA and restarting home assistant. 
![Screenshot 2025-01-10 072917](https://github.com/user-attachments/assets/64d9f70d-c34b-4add-8f5b-1c5219440330)

I also activated the Debug-Protokoll from home assistant KEBA integration - see attached file.
[home-assistant_keba_2025-01-10T06-33-20.196Z.log](https://github.com/user-attachments/files/18371707/home-assistant_keba_2025-01-10T06-33-20.196Z.log)

Regards,
Martin

**Comment by dannerph** [comment]
Could you please enable `sensor.keba_p30_current_hardware`. This value is used for the slider as maximum value.

**Comment by mebi2024** [comment]
Does someone have any ideas how to change 6A to 16A with a script?
My problem is, that customers are disappointed to load with 4kW instead fo 11kW and I have to change it back as soon as possible to 16A.
Does ist make sence to go to a higher HA version?

**Comment by dannerph** [comment]
The issue with setting the failsafe mode in the developer menu is due to some yet unknown issue in registering the charhing station to home assistant. I could not reproduce it so far. Probably I need to extend debug logging to check what is going on in your installation. (I am blocked with other work this week).

Regarding the failsafe mode issue, is it possible to set it in the web ui of the charging station? I do not own a x-series but I know it has a lot more options there. If not you can run the the underlying python library of this integration which also has a CLI: https://github.com/dannerph/keba-kecontact
In the CLI mode pnce connect to the charging station, enter "failsafe 0 0 0" to disable it.

You only have one charging station or do you have multiples connected in master/slave? 🤔

Was it working with older vetsion of the Integration? If yes you could downgrade to v3.x. if doing so, always remove the charging station from the device menu an re-add them afterwards.

**Comment by mebi2024** [comment]
Thank you again for the fast response!

I did not find "failsafe" mode in the web ui. Due to my OCCP connection to a charging provider I cannot use OCCP to the KEBA web connection (also used with the KEBA App on mobile). Maybe I can change the for testing mid of the week.

THanks for the CLI hint, but currently I don't know how to run this with python.

I have only one KEBA and no multiples (no master/slave)

I deinstalled KEBA integration and installed 3.0.3 and got the same error. I updated to 4.3.0 and still the same error. Maybe I have to try 3.0.1

Is it possible, that the HA version 2025.x causes the error?

**Comment by dannerph** [comment]
In your case, it is mainly related to the failsafe mode switching back the current to 6A after a while. Changing settings in OCCP will probably not help.

I need to find out why the configuration is no stored correctly, unfortunately earliest next week.

**Comment by schmersgahoven** [comment]
Just an idea if it's really urgent to deactivate failsafe. You can try via modbus integration.

Fist set up modbus in your configuration.yaml
example:

![Image](https://github.com/user-attachments/assets/1dd62e9d-411e-41df-857b-033815cc5407)

You neet at least one entity so I take Failsafe current. And change to your IP adress of charging station

restart home assistant and go to action and write register as described in the KEBA manual

![Image](https://github.com/user-attachments/assets/4c6e3898-23b2-4c70-a5a9-972ec2e3b3e6)

![Image](https://github.com/user-attachments/assets/fb689522-6d5b-4197-acad-c1ea2e781caf)

![Image](https://github.com/user-attachments/assets/0aba374f-b3bf-467c-be4a-78f92ca4da59)

Example for Failsafe Timeout:

![Image](https://github.com/user-attachments/assets/856b488c-1d69-4a9e-a0e1-16b1cde3663e)

Afterwards you have to delete added lines in configuration.yaml and restart Home Assistant. Otherwise maybe you will have problem with this integration because both will communicate with KEBA
